import { Component, OnInit } from '@angular/core';
import { MediaQueryService } from '@services/media-query.service';
import { DeviceGroups } from '@enums/device-groups.enum';
import { routerTransition } from '@animations/router.animations';
import { RouterModule } from '@angular/router';

// For Carousel, and animations
import { NguCarousel, NguCarouselStore } from '@ngu/carousel';
import { HostListener, Inject, ViewChild } from '@angular/core';
import { listAppears } from '@animations/list.animations';
import { floatingShip } from '@animations/floatingShip.animations';
import { NgClass } from '@angular/common';
import { trigger } from '@angular/animations';

@Component({
  selector: 'fly-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  animations: [routerTransition, listAppears, floatingShip],
  host: { '[@routerTransition]': '' }
})
export class HomeComponent implements OnInit {
  @ViewChild('doList') divList;

  // For animations on mobile
  phoneListStates: string[] = ['', '', '', '', ''];

  public listStates: string[] = ['inactive', 'inactive', 'inactive', 'inactive', 'inactive'];
  public currentList = 1;
  public services = [
    {
      title: 'Apps & Tools',
      image: '../../../assets/apps-tools.svg',
      description: `
        We believe in powerful, smart, scalable apps and tools that help people work better and faster,
        improve conversion rates, or just make life more interesting.
        You shouldn’t have to settle for less when you’re just getting started.
      `,
    },
    {
      title: 'Layout & Design',
      image: './../../assets/layout-design.svg',
      description: `
        We’re passionate about clean design and intuitive user experience.
        With careful use of line, color, and angle we can tell stories, display dense data, and keep users on your page longer.
        Better results start with good design.
      `,
    },
    {
      title: 'Icons & Graphics',
      image: '../../../assets/icons-graphics.svg',
      description: `
        It’s often the little things that set you apart.
        Not every MVP has to be built with standard cookie-cutter elements.
        One-of-a-kind, custom graphics and icons can captivate your audience, convey your meaning, and direct attention.
      `,
    },
    {
      title: 'Validation & Refinement',
      image: '../../../assets/validation-refinement.svg',
      description: `
        Turning an idea to a business takes diligence and iteration.
        You have to think about scalability, monetization, technology, timing, targeted marketing, and more.
        Don’t finalize your idea in a vacuum; get the feedback and guidance you didn’t know you needed.
      `,
    },
    {
      title: 'Execution & Strategy',
      image: '../../../assets/execution-strategy.svg',
      description: `
        Startup failure is rarely due to a bad idea.
        A kink in your process or business model can derail everything without warning.
        We’ll put information and analytics at your fingertips along with a sound strategy and deft execution.
      `,
    },
    {
      title: 'Take-off',
      image: '../../../assets/takeoff.svg',
      description: `
        Great minds shake empty fists at wealthy founders saying “that was my idea!” and it’s usually true.
        Ideas in the queue mean nothing. Flight will guide you through a pre-flight check, taxi to the runway, and lift off!
        Air traffic control stays with you to ensure a safe landing.
      `,
    },
  ];

  public paths = [
    {
      title: 'Meteoric Take-off',
      description: `
        Rapid user adoption of a new product or service.
        Usually best suited for low-margin, mass-market ideas.
        Helps make your idea presentation ready.
      `,
    },
    {
      title: 'Cash Flow Positive',
      description: `
        More money is generated by the product than it consumes.
        Usually best suited for sales-heavy, high-margin products or services.
        Helps make your idea presentation ready.
      `,
    },
    {
      title: 'Presentation Ready',
      description: `
        The product or idea is compelling to investors and early adopters.
        Your elevator pitch is legitimate and you have some skin in the game.
        Ideally, you have some cash flow and/or lots of customers.
      `,
    },
  ];

  public team = [
    {
      name: 'Jacob Johnston',
      title: 'Architect & Founder',
      photo: '../../../assets/jacob-sq.jpg',
      bio: `
        A lover of science and technology, seeking out innovative and inspiring tools and tech to enhance our
        clients' entrepreneurial endeavors.
        Jacob takes great pleasure in creating powerful, performant, dynamic web applications and beautiful, intuitive user interfaces.
        His other passion is entrepreneurship, graduating with a concentration in entrepreneurial studies.
        He's always following case studies and the latest findings about what works and doesn't for startups and growing businesses.
        He really likes working with innovators.
      `,
      socials: [
        {
          url: 'https://www.linkedin.com/in/jacobgjohnston/',
          icon: 'fa-linkedin',
        },
        {
          url: 'https://github.com/Methodician',
          icon: 'fa-github-square',
        },
      ],
    },
    {
      name: 'Tricia Mendoza',
      title: 'Product Designer',
      photo: '../../../assets/tricia-sq.jpg',
      bio: `
        Making sure not to get tempted with the financial stability that comes with pursuing a medical career,
        she stayed on track by achieving a Bachelors Degree in Illustration from California State University, Long Beach.
        She plans to fulfill her childhood prophecy of furthering her claim in the design world by using shapes,
        lines, and composition in ways they thought couldn't be done.
        Watch out for her, as she is just getting warmed up.
      `,
      socials: [
        {
          url: 'https://www.linkedin.com/in/triciamendoza/',
          icon: 'fa-linkedin',
        },
        {
          url: 'http://tvmopperator.com/',
          icon: 'fas fa-square',
        },
      ],
    },
    {
      name: 'Joe Parsley',
      title: 'UI/UX Engineer',
      photo: '../../../assets/joe.jpg',
      bio: `
        Born and raised in Oregon, Joe enjoys all of the amazing things the Pacific Northwest has to offer.
        He's all about everything nerdy and has a profound love for designing and programming.
        Being able to take someone's idea and turn it into a virtually physical piece of art that can be enjoyed
        on any screen is what keeps Joe going.
        When he's not programming or designing, you can find Joe playing DnD,
         jamming with his band, hiking or backpacking with his friends.
      `,
      socials: [
        {
          url: 'https://www.linkedin.com/in/joe-parsley',
          icon: 'fa-linkedin',
        },
        {
          url: 'https://github.com/joeparsley',
          icon: 'fa-github-square',
        },
      ],
    },
    {
      name: 'Aubrey Masten',
      title: 'Software Developer',
      photo: '../../../assets/aubrey.jpg',
      bio: `
        A problem solver compelled by challenges and learning opportunities, Aubrey delights in simple, well built systems.
        Introduced to programming at an early age, he discovered a lifelong passion.
        An eternal student, motivated by the opportunity to listen and learn from those around him.
        He tries to bring the joy of designing and building a system to that system's
        audience and build delightful and intuitive experiences.
        The process of building applications excites him as well as opportunities to work with others to help them realize their vision.
      `,
      socials: [
        {
          url: 'https://www.linkedin.com/in/aubreymasten/',
          icon: 'fa-linkedin',
        },
        {
          url: 'https://github.com/aubreymasten',
          icon: 'fa-github-square',
        },
      ],
    },
  ];

  // TODO: recreate below icon in more sustainable format
  //   <a class="link-wrapper" href="http://tvmopperator.com/">
  //   <svg id="eggy" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 31 31">
  //     <defs>
  //       <style>
  //         .cls-1 { fill:#ff5174; }
  //       </style>
  //     </defs>
  //     <title>tricia-icon</title>
  // tslint:disable-next-line:max-line-length
  //     <path class="cls-1 eggy" d="M27.8,0H3.2A3.2,3.2,0,0,0,0,3.2V27.8A3.2,3.2,0,0,0,3.2,31H27.8A3.2,3.2,0,0,0,31,27.8V3.2A3.2,3.2,0,0,0,27.8,0ZM22.06,19.56c-.9,0-1.89-.11-2.24.29a7.44,7.44,0,0,1-3.11,2,15.83,15.83,0,0,1-5.24,1A19,19,0,0,1,5.75,22a2.85,2.85,0,0,1-2.12-2.54c0-1.52,1.46-1.2,1.51-3.36,0-1.4,1.61-2.62,3.91-3.19h0a1.51,1.51,0,0,0,.13-.29,5.18,5.18,0,0,1,1.22-2.22,7.05,7.05,0,0,1,4-1.83c2.75-.37,5.69.59,6.52,2.08a1.13,1.13,0,0,0,.1.13l.13.14a.32.32,0,0,0,.16.09,2.36,2.36,0,0,0,.49.1c3,.44,5.23,2.2,5.23,4.38S24.92,19.56,22.06,19.56Z" transform="translate(0 0)"/>
  //     <path class="cls-1 eggy" d="M20.8,11.25l0-.08c-.54-1.31-3.27-2.65-6.31-2.24a6.61,6.61,0,0,0-3.81,1.72,4.86,4.86,0,0,0-1.08,2.1,1.73,1.73,0,0,1-.06.18l-.06.16a1,1,0,0,0,0,.5c.1.72.05,1.2,1,1.57a12.79,12.79,0,0,0,5.3.37c1.56-.21,3.61-.45,4.54-1.21s.68-2,.57-2.87A.71.71,0,0,0,20.8,11.25Z" transform="translate(0 0)"/>
  //   </svg>
  // </a>

  floatingShip: string = 'down';

  currentDevice: DeviceGroups = DeviceGroups.desktop;

  constructor(
    private mediaSvc: MediaQueryService
  ) {
    //  Create a new SPA "pageview" for Mouseflow:
    const win = window as any;
    win._mfq = win._mfq || [];
    win._mfq.push(['newPageView', '/home']);
  }

  ngOnInit() {
    this.mediaSvc.deviceGroup.subscribe(group => {
      this.currentDevice = group;
    });

    if (this.currentDevice.includes('phone')) {
      return;
    } else {
      setInterval(() => {
        this.floatingShip === 'up' ? this.floatingShip = 'down' : this.floatingShip = 'up';
      }, 3000);
    }
  }
  // END of onInit

  // @HostListener("window:scroll", []) windowScroll() {
  //   var triggerPosition: number = this.divList.nativeElement.offsetTop - (window.innerHeight / 2);
  //   // console.log("this is the trigger position ", this.divList.nativeElement.offsetTop);
  //   if (window.pageYOffset >= triggerPosition) {
  //     if (this.currentDevice.includes("phone") && this.listStates[0] === "inactive") {
  //       let time = 0;
  //       for (let i = 0; i < this.phoneListStates.length; i++) {
  //         setTimeout(() => {
  //           this.phoneListStates[i] = "list-appear";
  //         }, time);
  //         time = (i + 1) * 800;
  //       }
  //     } else {
  //       console.log("animation is playing");
  //       this.listStates[3] = "active3";
  //       this.listStates[0] = "active";
  //     }
  //   } else {
  //     // if you want to make it a repeating animation
  //     // for (let i = 0; i < this.listStates.length; i++){
  //     //   this.listStates[i] = "inactive";
  //     //   this.currentList = 1;
  //     // }
  //   }
  // }

  // animationDone(e: any) {
  //   console.log("list state 2", this.listStates[2]);
  //   // this.listStates[this.currentList] = "active";
  //   // if (this.listStates[0] === "active" && this.currentList < 5){
  //   //   console.log(this.currentList);
  //   //   this.listStates[this.currentList] = "active"+this.currentList;
  //   //   this.currentList++;
  //   // }
  //   if (this.listStates[2] === "active2") {
  //     this.listStates[4] = "active4";
  //   } else if (this.listStates[0] === "active" && this.currentList === 1) {
  //     this.listStates[1] = "active1";
  //     this.listStates[2] = "active2";
  //     console.log(this.listStates);
  //   }
  // }
}
